tap 'mobile-dev-inc/tap'
brew 'nvm'
brew 'libffi'
brew 'lcdf-typetools'
cask 'brooklyn'
brew 'ruby'
brew 'yarn'
cask 'slack'
cask 'sublime-text'
cask 'github'
cask 'alfred'
cask 'notion'
cask 'xscope'
cask 'spotify'
brew 'duti'
cask 'google-drive'
brew 'mas'
cask 'figma'
cask 'font-sf-pro'
cask 'font-manrope'
cask 'zoom'
cask 'sf-symbols'
brew 'typescript'
brew 'innoextract'
cask 'webex'
brew 'rbenv'
brew 'rbenv-bundler'
cask 'keyboardcleantool'
cask 'google-chrome'
cask 'claude'
cask 'claude-code@latest'
cask 'icon-composer'
brew 'firebase-cli'
cask 'gcloud-cli'
brew 'openjdk@21'
cask 'betterdisplay'
brew 'ffmpeg'
cask 'utm'
brew 'stripe-cli'
brew 'git-lfs'
cask 'android-studio'
cask 'openwhispr'
brew 'mobile-dev-inc/tap/maestro'

mas 'Vivid', id: 6443470555
mas 'Due', id: 524373870
mas 'Amphetamine', id: 937984704
mas 'Magnet', id: 441258766
mas 'Microsoft Word', id: 462054704
mas 'Microsoft Excel', id: 462058435
mas 'WhatsApp', id: 310633997
mas 'Xcode', id: 497799835
mas 'NordVPN: VPN Fast & Secure', id: 905953485
mas 'OurCal Calendar Messenger', id: 6461773071
mas 'Streaks', id: 963034692
